apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: testzhangze-docker
spec:
  encryptedData:
    .dockerconfigjson: AQBAGAOkY+0PH6uuFG6S/zd7VaFZMcJVx/pySwZTmL+ccfSjja+O6huUoc+hZPZqO836rq2rNtOihc+m5spXU2MxgYHFtTDCfhgleYLX/jj9Ol0LhGs5NS5m7UEinOiY3A8AKX3tW6F6FDQcxzKqRwWrXlFd0/+jaQdJkkca5qATTK7Ypy6PjkaEEWRPPigQU9hNegi6WO2TdmZeCe0ows+ZOYF3s9FX2qKfcFPDZJZrqkZh2AYp+snrPUvaadwNna/B+SYc2fLoXwt4ZAR0w09154AjzdTFxw8OPgqv0Q8yLr1o+TdYsMWumNfceqFCucrBkDlkFo23LhPAuBeKANz7R6UWiQpusKPWj5ua1IR3ShqK3XIM1yIDknGMhN5+SrRKiCbXMCP2qm3Zw/sHdZ/f0wulZdgLvFF6SKK36qU/zu5waseVn7+mPnrajaVIDe663ZNPGV69DyBihedvZJAPWHCjbA5eI23SxHcaBZJSIs3wso/BIQhSCaUTphTqE3f+mQ3w7Ay0PJZofBAO6W1t2JSIfJi+QngOnVgMklRghFEheEmryCbdZ8oAvkQUOGDYp76kwVrHLSXlBgAtGXC4FmdqAmXAgUgS
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: testzhangze-docker
    type: kubernetes.io/dockerconfigjson
